spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fake_twitter
    username:
    password:
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql